### ISSUE TITLE
How can I reference terraform remote state in my k8s manifests? CRD for terraform remote state?

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-kubernetes#1038]
Im using CRDs (service catalogue, etc) to create cloud resources inside my k8s manifests

but all my base infrastructure is defined in terraform

What I want is to link the two

For example I terraform my VPCs and subnets and write terraform outputs for the VPC and subnet IDs
Then in my deployment manifests lets say I want to create a database with a CRD. I want to reference the terraform remote state and reference the VPC/subnet ID and retrieve the subnet ip range and other info. 

another example is that I terraform my route53 zones. I have a CRD that can create DNS records for my deployments. So I want to reference the remote state I output for the route53 zone and retrieve the route53 zone ID (instead of having to pass that in some other way)

Doing this I dont have to hard code VPC IDs and other stuff. It can all come from terraform state and that becomes the source of truth

**Comment by alexsomesan** [comment]
@red8888 It would help us to know more about which tools you use to manage those CRDs, in order to offer a more precise solution.
Nevertheless, since you mentioned you already have outputs defined in Terraform for the values you are interested in, then you can used the `terraform` CLI to extract them via the `output` command.

For example, for an output called `vpc-id`, after the configuration has been applied you can run this command in the directory that contains the state file:
`terraform output vpc-id` and it should print the value of the output.
Alternatively, you can pass the complete path to the state file in command via the `-state` argument and then you can run it from any location.

Hope this is close to what you wanted to know. If you can give more details about your workflow, we can try to find better options.

**Comment by red8888** [comment]
Im looking for an actual integration here though. Like how I can use terraform remote state imports or for example how I can reference a "shared" cloud formation stack- I dont want to do some scripty thing to link things together.

I was wonder if the tf operator supported this. Im talking about using this operators CRDs to create resources and also having a way of referencing remote state. 

So using this operator I can, for example, describe an "EC2" resource and in that resource definition where I need to specify the  VPC/subnet ID I reference the remote state output of another tf workspace for the values.
