### ISSUE TITLE
How can i create jks secret ??

### ISSUE THREAD

**Issue by supamastec** [hashicorp/terraform-provider-kubernetes#1075]
I cannot create jks secret ,I found this issue solve last year [JKS-secret-issue-604](https://github.com/hashicorp/terraform-provider-kubernetes/pull/604/files/73381f8a1a4f35af457495d5183eaebebd0bdf21#)
But I don't see any code about fix that issue in stable version.

**Comment by sosimon** [comment]
Following the thread will lead you to https://github.com/hashicorp/terraform-provider-kubernetes/issues/901

There is a fix but it hasn't been merged yet.

**Comment by dak1n1** [comment]
Thanks for this bug report! It is on our list to implement eventually, but we're accepting contributions in case any community members are able to get to it sooner. I'll bring it up in our triage meeting again, since it seems to be gaining popularity. We'll track the issue in #901 and close this one as a duplicate. Thanks
