### ISSUE TITLE
Could not mount Ephemeral CSI Volume to Pod

### ISSUE THREAD

**Issue by bsomes** [hashicorp/terraform-provider-kubernetes#1086]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.14.2
Kubernetes provider version: 1.13.3
Kubernetes version: 1.18.10
```

### Affected Resource(s)

* kubernetes_deployment
* kubernetes_pod
### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "kubernetes_deployment" "app_deployment" {
  metadata {
    name = "app"
    labels = {
      "io.kompose.service" = "app"
    }
  }

  spec {
    replicas = 1
    strategy {
      type = "Recreate"
    }
    selector {
      match_labels = {
        "io.kompose.service" = "app"
      }
    }

    template {
      metadata {
        labels = {
          "io.kompose.service" = "app"
        }
      }
      spec {
        container {
          image   = "${data.azurerm_container_registry.registry.login_server}/app:${var.app_version}"
          name    = "app"
          command = ["app"]
          env {
            name  = "DB_HOST"
            value = azurerm_postgresql_server.db-server.fqdn
          }
          env {
            name  = "DB_SERVER"
            value = azurerm_postgresql_server.db-server.name
          }
          env {
            name  = "DB_PASSWORD_FILE"
            value = "/secrets/db-pwd"
          }
          env {
            name  = "DB_USER_FILE"
            value = "/secrets/db-usr"
          }
          env {
            name  = "DB_PORT"
            value = "5432"
          }
          env {
            name  = "HTTPS_PORT"
            value = ":8088"
          }
          port {
            container_port = 8080
          }
          resources {
            limits {
              memory = "500M"
              cpu    = "1024m"
            }
            requests {
              memory = "128Mi"
              cpu    = "500m"
            }
          }
          volume_mount {
            name       = "secrets-store"
            mount_path = "/secrets"
            read_only  = true
          }
        }
        restart_policy = "Always"
        volume {
          name = "secrets-store"
          csi {
            driver        = "secrets-store.csi.k8s.io"
            read_only     = true
            volume_handle = "kv"
            volume_attributes = {
              "secretProviderClass" = "azure-keyvault"
            }
            node_publish_secret_ref {
              name      = "secrets-store-creds"
              namespace = "default"
            }
          }
        }
      }
    }
  }
}

```

### Steps to Reproduce

1. Create a kubernetes cluster configured according to the [Tutorial: Configure and run the Azure Key Vault provider for the Secrets Store CSI driver on Kubernetes](https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes) (including installing the helm chart and creating the SecretProviderClass)
1. terraform apply

### Expected Behavior
What should have happened?
It should create the deployment with the correct CSI volume. 
```bash
kubectl describe deployment app 
```
Should have something like this in the "Volumes" section
secrets-store:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:            
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=azure-keyvault
### Actual Behavior
What actually happened?
Terraform tried to create the deployment indefinitely. 
When running
```bash
kubectl describe deployment app
```
The "Volumes" section looked like
secrets-store:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  
### Important Factoids

I noticed that in the docs there isn't a "csi" option for the "volume" block in the deployment or pod resource. It let me run it though. 
### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rtrive** [comment]
**Terraform Version, Provider Version and Kubernetes Version**
```
Terraform version: 0.14.5
Kubernetes provider version: 1.13.3
Kubernetes version: 1.18.12-gke.1205
```

Same problem with csi.cert-manager.io

```hcl
        volume {
          name = "tls"
          csi {
            driver = "csi.cert-manager.io"
            volume_attributes = {
              "csi.cert-manager.io/issuer-name" = "ca-issuer"
              "csi.cert-manager.io/dns-names"   = "my-service.namespace.svc.cluster.local"
              "csi.cert-manager.io/uri-sans"    = "spiffe://my-service.namespace.svc.cluster.local"
            }
            volume_handle = "csi"
            
          }
        }
```
I'm trying to create an ephemeral volume to mount tls certificates but it creates an emptyDir with no files.
If i try the same code but with original yaml it works

**Comment by mattduguid** [comment]
> **Terraform Version, Provider Version and Kubernetes Version**
> 
> ```
> Terraform version: 0.14.5
> Kubernetes provider version: 1.13.3
> Kubernetes version: 1.18.12-gke.1205
> ```
> 
> Same problem with csi.cert-manager.io
> 
> ```terraform
>         volume {
>           name = "tls"
>           csi {
>             driver = "csi.cert-manager.io"
>             volume_attributes = {
>               "csi.cert-manager.io/issuer-name" = "ca-issuer"
>               "csi.cert-manager.io/dns-names"   = "my-service.namespace.svc.cluster.local"
>               "csi.cert-manager.io/uri-sans"    = "spiffe://my-service.namespace.svc.cluster.local"
>             }
>             volume_handle = "csi"
>             
>           }
>         }
> ```
> 
> I'm trying to create an ephemeral volume to mount tls certificates but it creates an emptyDir with no files.
> If i try the same code but with original yaml it works

same issue here, i can get this all working using yaml applied with kubectl but using terraform and kubernetes provider everything works without error but the mount point is an emptydir, have you had any further progress with this?

**Comment by mattduguid** [comment]
aks kubernetes v1.19.11
terraform v0.15.1
kubernetes provider v2.3.2
helm provider v2.2.0
csi-secrets-store-provider-azure v0.0.16

ive captured csi logs from both a working solution (kubectl & yaml) vs non working solution (terraform) and there are no errors, we just fail to see the secrets mount

<details>
  <summary>Show logs</summary>
  
[WORKING - DEPLOYED VIA KUBECTL + YAML]

csi-secrets-store-provider-azure-xxxxx

I0617 01:36:10.383080       1 main.go:54] Starting Azure Key Vault Provider version: 0.0.12
I0617 01:36:10.481351       1 main.go:99] Listening for connections on address: //provider/azure.sock
I0617 03:30:53.136656       1 provider.go:244] "unmarshaled key vault objects" keyVaultObjects=[{ObjectName:aks-fqdn ObjectAlias: ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:} {ObjectName:aks-username ObjectAlias: ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:}] count=2 pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:53.136700       1 provider.go:255] "fetching object from key vault" objectName="aks-fqdn" objectType="secret" keyvault="ma##### REDACTED #####01" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:53.136822       1 auth.go:133] "using user-assigned managed identity to retrieve access token" clientID="be59##### REDACTED #####019e" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:54.679510       1 provider.go:288] "successfully wrote file" file="aks-fqdn" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:54.679541       1 provider.go:255] "fetching object from key vault" objectName="aks-username" objectType="secret" keyvault="ma##### REDACTED #####01" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:54.679860       1 auth.go:133] "using user-assigned managed identity to retrieve access token" clientID="be59##### REDACTED #####019e" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:55.079464       1 provider.go:288] "successfully wrote file" file="aks-username" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:52:08.623400       1 provider.go:244] "unmarshaled key vault objects" keyVaultObjects=[{ObjectName:aks-fqdn ObjectAlias: ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:} {ObjectName:aks-username ObjectAlias: ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:}] count=2 pod="helloworld/helloworld-66c7868498-w9gxc"
I0617 03:52:08.623430       1 provider.go:255] "fetching object from key vault" objectName="aks-fqdn" objectType="secret" keyvault="ma##### REDACTED #####01" pod="helloworld/helloworld-66c7868498-w9gxc"
***CONTINUES***

csi-secrets-store-provider-azure-secrets-store-csi-driver-xxxxx-liveness-probe

I0617 01:36:10.029619       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 01:36:12.046056       1 main.go:149] calling CSI driver to discover driver name
I0617 01:36:12.047224       1 main.go:155] CSI driver name: "secrets-store.csi.k8s.io"
I0617 01:36:12.047250       1 main.go:183] ServeMux listening at "0.0.0.0:9808"
I0617 01:36:47.605609       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 01:37:02.605634       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 01:37:17.605667       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 01:37:32.605669       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 01:37:47.605584       1 connection.go:153] Connecting to unix:///csi/csi.sock
***CONTINUES***

csi-secrets-store-provider-azure-secrets-store-csi-driver-xxxxx-node-driver-registrar

I0617 01:36:09.660746       1 main.go:113] Version: v2.1.0-0-g80d42f24
I0617 01:36:09.661212       1 main.go:137] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0617 01:36:09.661252       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 01:36:11.717751       1 main.go:144] Calling CSI driver to discover driver name
I0617 01:36:11.717774       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0617 01:36:11.717778       1 connection.go:183] GRPC request: {}
I0617 01:36:11.730941       1 connection.go:185] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.19"}
I0617 01:36:11.730998       1 connection.go:186] GRPC error: <nil>
I0617 01:36:11.731005       1 main.go:154] CSI driver name: "secrets-store.csi.k8s.io"
I0617 01:36:11.731092       1 node_register.go:52] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0617 01:36:11.735523       1 node_register.go:61] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0617 01:36:11.735619       1 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0617 01:36:11.737539       1 main.go:80] Received GetInfo call: &InfoRequest{}
I0617 01:36:11.766489       1 main.go:90] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
***CONTINUES***

csi-secrets-store-provider-azure-secrets-store-csi-driver-xxxxx-secrets-store

I0617 01:36:09.879711       1 exporter.go:33] metrics backend: prometheus
I0617 01:36:10.804792       1 main.go:143] starting manager
I0617 01:36:11.706982       1 secrets-store.go:88] Driver: secrets-store.csi.k8s.io 
I0617 01:36:11.707002       1 secrets-store.go:89] Version: v0.0.19, BuildTime: 2021-01-19-19:06
I0617 01:36:11.707006       1 secrets-store.go:90] Provider Volume Path: /etc/kubernetes/secrets-store-csi-providers
I0617 01:36:11.707009       1 secrets-store.go:92] GRPC supported provider: azure
I0617 01:36:11.707020       1 driver.go:80] "Enabling controller service capability" capability="CREATE_DELETE_VOLUME"
I0617 01:36:11.707037       1 driver.go:90] "Enabling volume access mode" mode="SINGLE_NODE_READER_ONLY"
I0617 01:36:11.707042       1 driver.go:90] "Enabling volume access mode" mode="MULTI_NODE_READER_ONLY"
I0617 01:36:11.707183       1 secrets-store.go:55] minimum compatible provider versions not specified with --min-provider-version
I0617 01:36:11.707322       1 server.go:111] Listening for connections on address: //csi/csi.sock
I0617 03:30:53.135895       1 nodeserver.go:300] "Using grpc client" provider="azure" pod="helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:55.090160       1 nodeserver.go:208] "node publish volume complete" targetPath="/var/lib/kubelet/pods/e2bb9e51-0dba-46b4-9307-30d5815ce0c9/volumes/kubernetes.io~csi/secrets-store-inline/mount" pod="helloworld/helloworld-6fbdf4b7c5-hwntc"
I0617 03:30:55.090261       1 secretproviderclasspodstatus_controller.go:183] "reconcile started" spcps="helloworld/helloworld-6fbdf4b7c5-hwntc-helloworld-keyvault-ma##### REDACTED #####01-helloworld"
I0617 03:30:55.502183       1 secretproviderclasspodstatus_controller.go:357] "successfully created Kubernetes secret" secret="helloworld/helloworld"
I0617 03:30:55.502231       1 secretproviderclasspodstatus_controller.go:329] "reconcile complete" spc="helloworld/keyvault-ma##### REDACTED #####01-helloworld" pod="helloworld/helloworld-6fbdf4b7c5-hwntc" spcps="helloworld/helloworld-6fbdf4b7c5-hwntc-helloworld-keyvault-ma##### REDACTED #####01-helloworld"
I0617 03:35:55.502615       1 secretproviderclasspodstatus_controller.go:183] "reconcile started" spcps="helloworld/helloworld-6fbdf4b7c5-hwntc-helloworld-keyvault-ma##### REDACTED #####01-helloworld"
I0617 03:35:55.502831       1 secretproviderclasspodstatus_controller.go:329] "reconcile complete" spc="helloworld/keyvault-ma##### REDACTED #####01-helloworld" pod="helloworld/helloworld-6fbdf4b7c5-hwntc" spcps="helloworld/helloworld-6fbdf4b7c5-hwntc-helloworld-keyvault-ma##### REDACTED #####01-helloworld"
I0617 03:40:55.503211       1 secretproviderclasspodstatus_controller.go:183] "reconcile started" spcps="helloworld/helloworld-6fbdf4b7c5-hwntc-helloworld-keyvault-ma##### REDACTED #####01-helloworld"
***CONTINUES***

[FAILED HAS EMPTYDIR AT VOLUME MOUNT POINT - DEPLOYED VIA TERRAFORM]

csi-secrets-store-provider-azure-xxxxx

I0617 05:33:58.644624       1 main.go:54] Starting Azure Key Vault Provider version: 0.0.12
I0617 05:33:58.644940       1 main.go:99] Listening for connections on address: //provider/azure.sock
***END***

csi-secrets-store-provider-azure-secrets-store-csi-driver-xxxxx-liveness-probe

I0617 05:33:58.385774       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 05:34:00.376234       1 main.go:149] calling CSI driver to discover driver name
I0617 05:34:00.380108       1 main.go:155] CSI driver name: "secrets-store.csi.k8s.io"
I0617 05:34:00.380129       1 main.go:183] ServeMux listening at "0.0.0.0:9808"
I0617 05:34:33.865392       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 05:34:48.864974       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 05:35:03.865480       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 05:35:18.865023       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 05:35:33.865046       1 connection.go:153] Connecting to unix:///csi/csi.sock
***CONTINUES***

csi-secrets-store-provider-azure-secrets-store-csi-driver-xxxxx-node-driver-registrar

I0617 05:33:57.898190       1 main.go:113] Version: v2.1.0-0-g80d42f24
I0617 05:33:57.898657       1 main.go:137] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0617 05:33:57.898680       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0617 05:34:00.802878       1 main.go:144] Calling CSI driver to discover driver name
I0617 05:34:00.802911       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0617 05:34:00.802916       1 connection.go:183] GRPC request: {}
I0617 05:34:00.806014       1 connection.go:185] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.19"}
I0617 05:34:00.806071       1 connection.go:186] GRPC error: <nil>
I0617 05:34:00.806079       1 main.go:154] CSI driver name: "secrets-store.csi.k8s.io"
I0617 05:34:00.806349       1 node_register.go:52] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sock
I0617 05:34:00.806673       1 node_register.go:61] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sock
I0617 05:34:00.806859       1 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0617 05:34:01.417283       1 main.go:80] Received GetInfo call: &InfoRequest{}
I0617 05:34:01.447188       1 main.go:90] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
***END***

csi-secrets-store-provider-azure-secrets-store-csi-driver-xxxxx-secrets-store

I0617 05:33:58.127787       1 exporter.go:33] metrics backend: prometheus
I0617 05:33:59.096641       1 main.go:143] starting manager
I0617 05:33:59.999036       1 secrets-store.go:88] Driver: secrets-store.csi.k8s.io 
I0617 05:33:59.999073       1 secrets-store.go:89] Version: v0.0.19, BuildTime: 2021-01-19-19:06
I0617 05:33:59.999078       1 secrets-store.go:90] Provider Volume Path: /etc/kubernetes/secrets-store-csi-providers
I0617 05:33:59.999082       1 secrets-store.go:92] GRPC supported provider: azure
I0617 05:33:59.999095       1 driver.go:80] "Enabling controller service capability" capability="CREATE_DELETE_VOLUME"
I0617 05:33:59.999106       1 driver.go:90] "Enabling volume access mode" mode="SINGLE_NODE_READER_ONLY"
I0617 05:33:59.999129       1 driver.go:90] "Enabling volume access mode" mode="MULTI_NODE_READER_ONLY"
I0617 05:33:59.999440       1 secrets-store.go:55] minimum compatible provider versions not specified with --min-provider-version
I0617 05:33:59.999675       1 server.go:111] Listening for connections on address: //csi/csi.sock
***END***

</details>

**Comment by mattduguid** [comment]
worked around the above issue by using the kubernetes-alpha provider for the deployment and converted the deployment yaml to hcl via command below and all working

echo 'yamldecode(file("deployment.yaml"))' | terraform console

**Comment by shicholas** [comment]
Thanks for that workaround @mattduguid, I think this can work if `volume_handle` wasn't a required attribute in TF. This attribute does not exist for ephemeral volumes which Azure uses here.

**Comment by XciD** [comment]
Hello, any update on this ?

**Comment by sombralibre** [comment]
Hi there, any update for this issue, seems like the PR #1092 will solve this issue.
