### ISSUE TITLE
upgrade to v2 seems to perpetually diff against cron_job optional parameters

### ISSUE THREAD

**Issue by drcca** [hashicorp/terraform-provider-kubernetes#1139]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 0.14.5
Kubernetes provider version: Running on Terraform Cloud - no specific version specified in config (so guessing v2.0.1)
Kubernetes version: 1.15.12-gke.20
```

### Affected Resource(s)
- kubernetes_cron_job

### Terraform Configuration Files
https://gist.github.com/drcca/07c31fefa016d66f120700cb0aa76b5e

### Debug Output
https://gist.github.com/drcca/27d0ec4a9a35a3e5ba231707371dee75

### Steps to Reproduce
Ran plan on Terraform Cloud for this configuration

### Expected Behavior
Would not expect a diff for any optional values. Would also not have expected a force replacement. 

### Actual Behavior
After upgrade to v2 this started to do a force replacement where before it just made an update.

### Important Factoids
N/A

### References
N/A

**Comment by dak1n1** [comment]
Hi! Thanks for this bug report. You're right that this is a bug. I took a quick look at your config to see what we can do to work around it in the mean time. I saw the issue is coming from a variable that updates the container's image version. Here's the line I'm referring to in the config:

```
            container {
              image = "gcr.io/<redacted>/<redacted>:${var.image_commit_hash}"
```

I suspect that this variable `${var.image_commit_hash}` is updating unexpectedly and triggering the replacement of the CronJob. In the output below, you can see the hash has changed, which triggers the replacement of the CronJob:

```
                              ~ image                      = "gcr.io/<redacted>/<redacted>:8291d16c69a47d002800534b8364d3cd6cf933ce" -> "gcr.io/<redacted>/<redacted>:4720ba0b79f8af0013e34c4586e1e369913e344e" # forces replacement
```

You could work around it temporarily by keeping the image version consistent until we fix the bug on the provider side. What we need to do on our side is ensure that CronJobs can update their PodSpecs in-place. In contrast to Jobs, which cannot update this field without replacing the entire object, the CronJob should be more flexible and allow replacement of mutable PodSpec fields, such as the `image` in this case. This is related to some work I did in [this PR](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1074) but it looks like I missed this particular case for CronJobs.

For the null diffs, we could try doing an SDK update to see if that cleans up the output during `terraform plan`. I see this commit went into the SDK recently, related to empty diffs. https://github.com/hashicorp/terraform-plugin-sdk/commit/1607a0a4fada076f3fba5c37f67060b3b7c4b1ef

**Comment by drcca** [comment]
@dak1n1 Thanks Stef for checking this out. I appreciate it!

The update to that variable is expected. That's essentially how I do new code pushes. I update the single variable and all the needed deployments/cronjobs get updated. So, the thing about this is that this *used* to work. I don't know if that helps at all. Hopefully that jives with that PR you referenced.

As for the null diffs, I thought about just specifying some of these in order to get the plan to not diff but figured that it probably wasn't worth it since the image would force the replacement anyway. AND, one of the values had more semantics behind it which I didn't want to mess up (active_deadline_seconds)
