### ISSUE TITLE
Alternative to load_config_file = false?

### ISSUE THREAD

**Issue by AlteredParadox** [hashicorp/terraform-provider-kubernetes#1162]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: v0.13.5
Kubernetes Provider version: v2.0.2
Kubernetes version: v1.19.3
```
## Terraform configuration
```hcl
provider "kubernetes" {
	version                = "~> 2.0"
	host                   = var.ClusterEndpoint
	cluster_ca_certificate = try(base64decode(var.ClusterCertData), "")
	token                  = data.aws_eks_cluster_auth.cluster.token
	load_config_file       = false
}
```
## Error
```
Error: Kubernetes cluster unreachable: stat /home/cra/.kube/config: no such file or directory
```
## Question
Before upgrading the Kubernetes provider to v2.0.2, we used v1.13.3. In the earlier version we used load_config_file = false because we provide the credentials directly, as shown above, and don't want it to try load a non-existent file. But in the later version this is deprecated.
How do we replicate the behaviour now, and can that please be added to the documentation because there is little information on this?

**Comment by AlteredParadox** [comment]
In [this documentation](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-to-kubernetes-credentials-supplied-in-the-provider-block) it explains why it's been removed and by removing the `load_config_file` attribute the expected result is what we want but this isn't working.
I do not have `KUBE_CONFIG_PATH`, or `config_path` set.

**Comment by aareet** [comment]
Hi, recently @dak1n1 merged some examples of how to work with each major cloud with examples - I think that the EKS example from that list may help you - https://github.com/hashicorp/terraform-provider-kubernetes/pull/1115. Let us know if those aren't sufficient.

**Comment by dak1n1** [comment]
I've also got a change in the works that will basically give us the same functionality as `load_config_file = false`. The goal is to create a more intuitive workflow by throwing an error when two mutually-exclusive configuration options are used (for example, if you've added a `provider {}` block containing a token, it will use that token instead of pulling the configuration options from an environment variable that you might not even know is set). https://github.com/hashicorp/terraform-provider-kubernetes/pull/1141

**Comment by AlteredParadox** [comment]
I have fixed the issue. The problem was that the Helm provider also had to be upgraded to "~> 2.0".
