### ISSUE TITLE
Encryption configuration cannot be set on an existing cluster

### ISSUE THREAD

**Issue by gg-caylent** [hashicorp/terraform-provider-kubernetes#1182]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.14.5
Kubernetes provider version: 2.0.2
Kubernetes version: 1.18
```

### Affected Resource(s)

- aws_eks_cluster

### Terraform Configuration Files
```hcl
variable "region" {
  default = "us-west-2"
}

variable "map_accounts" {
  description = "Additional AWS account numbers to add to the aws-auth configmap."
  type        = list(string)

  default = [
    "777777777777",
    "888888888888",
  ]
}

variable "map_roles" {
  description = "Additional IAM roles to add to the aws-auth configmap."
  type = list(object({
    rolearn  = string
    username = string
    groups   = list(string)
  }))

  default = []
}

variable "map_users" {
  description = "Additional IAM users to add to the aws-auth configmap."
  type = list(object({
    userarn  = string
    username = string
    groups   = list(string)
  }))

  default = []
}

terraform {
  required_version = ">= 0.12.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "1.9.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.0.2"
    }

  }
}

provider "aws" {
  region = var.region
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.eks-cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-cluster.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.eks-cluster.token
  }
}

provider "kubectl" {
  host                   = data.aws_eks_cluster.eks-cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.eks-cluster.token
  load_config_file       = false
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

data "aws_availability_zones" "available" {
}

locals {
  cluster_name = "test-eks-${random_string.suffix.result}"
}

resource "random_string" "suffix" {
  length  = 8
  special = false
}

resource "aws_kms_key" "eks" {
  description = "EKS Secret Encryption Key"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 2.48"

  name                 = "test-vpc"
  cidr                 = "10.0.0.0/16"
  azs                  = data.aws_availability_zones.available.names
  private_subnets      = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets       = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
  enable_nat_gateway   = true
  single_nat_gateway   = true
  enable_dns_hostnames = true

  public_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                      = "1"
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/${local.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"             = "1"
  }
}

module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = "1.18"
  subnets         = module.vpc.private_subnets
  version         = "v13.0.0"


  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]

  tags = {
    Environment = "test"
    GithubRepo  = "terraform-aws-eks"
    GithubOrg   = "terraform-aws-modules"
  }

  vpc_id = module.vpc.vpc_id

  worker_groups = [
    {
      name                 = "worker-group-1"
      instance_type        = "t3.small"
      additional_userdata  = "echo foo bar"
      asg_desired_capacity = 2
    },
  ]

  map_roles    = var.map_roles
  map_users    = var.map_users
  map_accounts = var.map_accounts
}
```

### Debug Output

Apply: https://gist.github.com/gg-caylent/62987fcf86f0877b092e630fc5d1b541
Subsequent plan: https://gist.github.com/gg-caylent/ce3a7b5794c734a2a7ac8320a3ce30c9 

### Steps to Reproduce
Without encryption and then enable encryption:

1.  Comment out the block: `cluster_encryption_config`
2. `terraform init`
3. `terraform apply` -> cluster created without encryption
3. Uncomment the `cluster_encryption_config` block
4. `terraform plan` -> Error, the provider defaults to localhost and loses credentials

Alternative method, created with encryption then disable:
1. `terraform init`
2. `terraform apply` -> cluster created with encryption
2.  Comment the `cluster_encryption_config` block
3. `terraform plan` -> Error, the provider defaults to localhost and loses credentials

### Expected Behavior
What should have happened?
The encryption configuration to be enabled after the block has been added.

### Actual Behavior
What actually happened?
The kubernetes provider seems to be losing the credentials and all access to the cluster if it already exists and you try to enable that afterwards, however it works if you create the cluster from scratch with the cluster_encryption_config enabled.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment]
Thanks for this detailed bug report! You're right that the Kubernetes provider is losing the credentials to the EKS cluster. There are a few causes behind this, which I'll try to explain. 

The first issue is that the EKS module uses the AWS provider and the Kubernetes provider in the same `terraform apply`. Terraform actually [can't reliably support](https://www.terraform.io/docs/language/providers/configuration.html) using one provider to configure another provider in a single apply like this, because there are certain times (like the scenario we see here) where the EKS cluster's credentials become unknown. (Specifically, to quote the docs, a provider's configuration values must `only reference values that are known before the configuration is applied`. This can't be done when a cluster is created/modified in the same apply as Kubernetes provider resources). 

So the EKS module is somewhat hindered by this limitation during subsequent plans/applies/deletes. The initial create works as long as the dependencies have been established in the user's config (generally by referencing cluster_id, like in your config). But that only works because we have deferred initialization in the Kubernetes provider, to try and accommodate this use case, despite it not being supported by Terraform.

The quickest work-around for this is to remove the Kubernetes resource from state prior to applying your change:

```
terraform state rm module.eks.kubernetes_config_map.aws_auth
terraform plan
```

Another potential fix is coming from the AWS provider. It seems that the EKS cluster is not supposed to be deleted/recreated in this case, but it's happening anyway. That bug is here: https://github.com/hashicorp/terraform-provider-aws/issues/17952

However, the most stable and reliable long-term solution would be to keep the Kubernetes provider resources in a separate state from the AWS resources. That is, use separate modules to configure them, and don't apply them both at the same time. You can disable the Kubernetes provider integration in the EKS module by setting `manage_aws_auth = false`. The downside is, then you'd have to manage the configmap separately. But you can see how they create it here, for reference.  https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a26c9fd0c9c880d5b99c438ad620e91dda957e10/aws_auth.tf#L65-L93
