### ISSUE TITLE
kubernetes_deployment ignores timeout settings

### ISSUE THREAD

**Issue by pduchnovsky** [hashicorp/terraform-provider-kubernetes#1202]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v0.14.7
Kubernetes provider version: v2.0.2
Kubernetes version: 1.18.12-gke.1210
```

### Affected Resource(s)
kubernetes_deployment

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "xxxxxxxxx" {
  for_each = jsondecode(var.vars)

  metadata {
    name = lower(each.key)
    labels = {
      app = lower(each.key)
    }
  }

  spec {
    selector {
      match_labels = {
        app = lower(each.key)
      }
    }

    template {
      metadata {
        labels = {
          app = lower(each.key)
        }
      }

      spec {
        container {
          image = "gcr.io/${var.project_name}/${var.image}"
          image_pull_policy = "IfNotPresent"
          name  = lower(each.key)
        }
      }
    }
  }
  timeouts {
    create = "15m"
    update = "15m"
  }
  wait_for_rollout = true
}
```

### Steps to Reproduce
Update deployed kubernetes deployment with new image version via variable and run.
Image is big - 12.5 GB, thus it takes long to pull and start, therefore the need of increased timeout.

### Expected Behavior
Updated deployed kubernetes deployment takes 12 minutes and it finishes off successfully since it accepts timeout setting of 15 minutes.

### Actual Behavior
Updated deployed kubernetes deployment takes 10 minutes and it fails with error:

kubernetes_deployment.xxxxx["xxxxx"]: Still modifying... [id=default/xxxxx, 10m0s elapsed]
**Error: Deployment exceeded its progress deadline**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
This looks to be because this resources create function will wait the specified timeout, but on the Kubernetes side it times out before then because the default `progressDeadlineSeconds` is 10 minutes for deployment. A workaround here is to set [progress_deadline_seconds](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#progress_deadline_seconds) to the same as your timeout. 

We should make this resource a bit more clever to take both of these things into account so you only have to set one.
