### ISSUE TITLE
Kubernetes provider deletes entire state when it can't connect and is dependent on other resources

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [hashicorp/terraform-provider-kubernetes#1412]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.0.3
Kubernetes provider version: v2.5.0
Kubernetes version: v1.19.7
```

### Affected Resource(s)
All resources under this provider seem to be affected.

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "test_namespace" {
  metadata {
    name = "test-namespace"
  }
}
```
+ Proper configuration to set up the kubernetes cluster within the same terraform configuration

### Steps to Reproduce
1. Apply configuration as usual
2. Block the connection to the kubernetes control plane through firewall, broken bastion host, etc.
3. Terraform refresh or apply. The resource will be removed from state.

### Expected Behavior
Provider when managing resources should confirm with kubernetes endpoint that resources are truly destroyed. Throw an error when the kubernetes provider cannot be reached and resources are currently provisioned.

### Actual Behavior
Provider assumed resources were already destroyed since the provider couldn't reach the kubernetes endpoint and consequently removed them from state (even though they still exist)

### Important Factoids
I'm using a bastion host with a strict IP security group to connect to the cluster. I test a broken connection by switching my IP using a VPN, making the bastion connection fail.
I created the kubernetes cluster and the kubernetes resources in the same terraform config. 

This is a big red flag according to the docs:
![image](https://user-images.githubusercontent.com/66089890/133827457-80d029b4-460c-4bb9-97ee-72de4c00f611.png)

So this is likely a problem on my behalf. This can be solved by using terragrunt to deploy the cluster and k8 config in two separate state files.

To verify this was indeed the issue I reran the k8 config using the terraform target mode and removed all dependencies. Provider threw a connection error as expected instead of deleting the state.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BrandonALXEllisSS** [comment]
Closing since it's user error. I'd love for the day when the cluster and config can be deployed simultaneously however.

**Comment by redeux** [comment]
Thanks for reopening this @BrandonALXEllisSS. For reference, this issue was first posted on [Reddit](https://www.reddit.com/r/Terraform/comments/pq2kd8/kubernetes_provider_awfully_trigger_happy_to/).

I requested Brandon reopen this issue so we can take a look at the UX in this scenario is see if there is a way to improve it.

**Comment by redeux** [comment]
Here's some additional context provided by @apparentlymart in the Reddit thread that I'm capturing here for posterity.

FWIW, from the details given here I can guess one way this could happen:

- if using an unknown value as the server URL the provider will, due to the SDK's behavior, see the URL as the empty string.
- The provider has a default value for the URL that points at localhost, perhaps? And so it ends up turning that empty string into a localhost URL.
- The OP happens to have a minikube or similar such K8S on localhost, so the provider succeeds in connecting rather than failing as it typically would in this case.
- Terraform asks the provider to refresh each of the objects, but those objects don't actually exist on localhost (they live in some other cluster) so it seems like they were deleted outside of Terraform and so need to be recreated.

This is just a guess, but maybe the OP can confirm if anything I said above seems like it might fit, even if I got some of the details not quite right.

FWIW, this situation where a misconfigured refresh can end up dropping things from the state is the main reason why recent Terraform has "refresh-only" plans as the modern alternative to "terraform refresh". In that case, you at least get an opportunity to see what the provider detected in the refresh step and cancel the plan if it doesn't seem right.

**Comment by BrandonALXEllisSS** [comment]
In my case, kubeconfig pointed by default to endpoints on localhost, but no local cluster or minikube was running. The endpoints were also randomly allocated ports chosen on my client machine (and this error happened consistently), so I don't think it had anything to do with accidentally pointing to a working cluster.
