### ISSUE TITLE
kubernetes_persistent_volume_claim documentation typo

### ISSUE THREAD

**Issue by adelmoradian** [hashicorp/terraform-provider-kubernetes#1413]
Hi! 

There seems to be small typo in the kubernetes_persistent_volume_claim documentation in Terraform registry website.
Under [`spec.resources`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/persistent_volume_claim#resources) arguments are `limits` and `requests`. 
I expect to see something like `requests.storage`.

**Comment by alexsomesan** [comment]
Hi! The documentation mentions that "requests" and "limits" are maps (https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/persistent_volume_claim#resources).

This means the keys of the map are not defined as part of the resource schema (because they are also not fixed in the Kubrenetes API spec: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#resourcerequirements-v1-core).

**Comment by alexsomesan** [comment]
If you feel this should be worded differently in any way, please feel free to open a PR.
