### ISSUE TITLE
kubernetes_manifest ignores empty maps when updating existing resources

### ISSUE THREAD

**Issue by flokli** [hashicorp/terraform-provider-kubernetes#1477]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
```

### Affected Resource(s)

https://github.com/hashicorp/terraform-provider-kubernetes/pull/1460 fixed empty maps getting omitted, but resources created with an earlier version of this provider are not updated.

Reported initially in https://github.com/hashicorp/terraform-provider-kubernetes/pull/1460#issuecomment-952762148

References: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1429#issuecomment-954496112

**Comment by jrhouston** [comment]
Hi @flokli – because the state was created by a provider version where the `kubernetes_manifest` resource was experimental we can't add any state migration for this. I would suggest running `terraform state rm`, then `terraform import` on the resource which should bring bring the resource up to date.

**Comment by flokli** [comment]
I recreated the resources in the meantime, but assume more people will stumble in this. A bit sad this is a wontfix, but ok :-/
