### ISSUE TITLE
Adjust .mod file to meet golang standards

### ISSUE THREAD

**Issue by KevinKlinger** [hashicorp/terraform-provider-kubernetes#1529]
### Description

From my point of view, the go.mod should be changed to hold the major version as a suffix.
The [go definition reference](https://go.dev/ref/mod#module-path) defines that:
"If the module is released at major version 2 or higher, the module path must end with a major version suffix like /v2. "

The reason why I'm asking for this is, that I'd like to consolidate this provider, but `go get` and `go download` are failing, as the .mod file for this project is not meeting the go standards.

Maybe I'm just too stupid, but I'm happy to hear your thoughts.

Cheers

**Comment by alexsomesan** [comment]
Hi! 

It's not immediately apparrent how this would be useful, since the provider is not designed to be consumed as a library. It would be interesting if you could share more details about your use-case.

Since this issue is rather old, I'm going to close it for now, but feel free to re-open if you want to discuss your use-case further.
