### ISSUE TITLE
Unsupported array of metadata 

### ISSUE THREAD

**Issue by JunjiUmeno** [hashicorp/terraform-provider-kubernetes#1575]
https://github.com/hashicorp/terraform-provider-kubernetes/blob/be047c2144356371e80598d342e54f8c0380c2cb/kubernetes/resource_kubernetes_pod.go#L65

I believe Kubernetes doesn't suppose any array of metadata. Your implementation made me confused here. https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/service

`    selector = {
      app = kubernetes_pod.example.metadata.0.labels.app
    }
`

Do you have any reason to that?

**Comment by alexsomesan** [comment]
Because of historical reasons in the provider SDK, the attribute paths require this peculiar "list-like" syntax. Unless you are actually dealing with a list attribute, the index is always zero, but it has to be present. This will be resolved in providers based on the current state-of-the-art terraform-provider-framework, but this provider predates the framework.
