### ISSUE TITLE
Unable to apply valid `kubernetes_manifest` resource.

### ISSUE THREAD

**Issue by juicemia** [hashicorp/terraform-provider-kubernetes#1581]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.1.2
Kubernetes provider version: 2.7.1
Kubernetes version: v1.20.10-gke.1600
```

### Affected Resource(s)

- `kubernetes_manifest`

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

Gist: https://gist.github.com/juicemia/fd41e3702e9234eb241f0d6cea5a70e3

### Debug Output

Output with `TF_LOG=debug`: https://gist.github.com/juicemia/6117bb835e9dda07f47119e54685b41e

### Panic Output

Panic output: https://gist.github.com/juicemia/d57020f84d9353e60618c156defa48dc

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
Kubernetes manifest is applied to the cluster.

### Actual Behavior
Terraform panics.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by juicemia** [comment]
I was able to work around the issue by splitting the `configPatch` array into two separate `kubernetes_manifest` resources. However, I still think this is a bug because the manifest is perfectly valid and works with `kubectl`.

**Comment by alexsomesan** [comment]
Hi! 

I can confirm the issue in provider version 2.7.1. Root cause is the CRD schema skipping type definitions for some attributes (the `x-preserve-unknown-fields` annotation). We have a partial fix for this already merged in main, that allows apply and destory of such resources. This will be released in the next day or two.
Updates might still be problematic and for that we have another fix in the works that will be part of the following release.

I can confirm the resource you reported here works with the fix I mentioned. Please try again as soon as the next release is out.

**Comment by juicemia** [comment]
Hi Alex,

I think for now we're going to keep our workaround in place.

Thank you for your response, I'm going to close the issue since there's a patch out.
