### ISSUE TITLE
Documentation for container section of Deployment is incorrect

### ISSUE THREAD

**Issue by simhnna** [hashicorp/terraform-provider-kubernetes#1673]
The documentation of the [container section](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#container) of deployments lists `resources` as:

> (Optional) Compute Resources required by this container. Cannot be updated.

K8s does allow updates to these fields. Is there a reason why terraform doesn't update these? My only option is to destroy/create or rename the resource so the changes are applied

**Comment by jrhouston** [comment]
This looks like a mistake in the documentation @simhnna – you can change any of the container fields in deployment because it's just part of the template. 

This may have been copied over from Pod where only some of the fields are editable, and updating the the resources of a Pod in place produces the following error: 

```
Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds
```

**Comment by srikanthuday** [comment]
I will work on this and submit PR later
