### ISSUE TITLE
kubernetes_labels and kubernetes_config_map_v1_data remove each others data from ConfigMap

### ISSUE THREAD

**Issue by apeabody** [hashicorp/terraform-provider-kubernetes#1690]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.7
Kubernetes provider version: 2.10
Kubernetes version: 1.22.8-gke.200
```

### Affected Resource(s)
- kubernetes_config_map_v1_data
- kubernetes_labels

### Terraform Configuration Files
```
resource "kubernetes_config_map_v1_data" "example" {
  metadata {
    name      = "kube-dns"
    namespace = "kube-system"
  }
  data = {
    upstreamNameservers = 
  }
}
resource "kubernetes_labels" "example" {
  api_version = "v1"
  kind        = "ConfigMap"
  metadata {
    name      = "kube-dns"
    namespace = "kube-system"
  }
  labels = {
    mylabel = 
  }
}
```

### Steps to Reproduce
1. `terraform apply` a kubernetes_config_map_v1_data to a ConfigMap
2. `terraform apply` a kubernetes_labels to the same ConfigMap

### Expected Behavior
Both the label and the ConfigMap data should be present.  Alternatively `kubernetes_config_map_v1_data` could support labels.

### Actual Behavior
Only the data from the most recent application of `kubernetes_config_map_v1_data` or `kubernetes_labels` persists

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by lebetz** [comment]
The same is true for usage of kubernetes_labels and kubernetes_annotations. Only the last applied one persists.

**Comment by jrhouston** [comment]
Looks like this is because of the [merge strategy](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy) server-side apply uses with field manager. What's happening here is that each of these resources currently use `Terraform` as their field manager name. Currently each of these resources crafts a patch containing the data (i.e labels, annotations, config data) it is concerned with. When you don't specify the pre-existing fields that are already managed by the `Terraform` field manager then they are removed by the server-side apply. 

So, we have a few options here:

1. Read all of the data belonging to the `Terraform` field manager and add that to the patch so it is preserved. 
2. Use different field manager names for each resource, e.g containing the resource name/id
3. Make the field manager configurable and leave it up to the user 

Option #1 seems like the most sensible, although we would need to solve for the race condition where we have Terraform multiple resources patching the same Kubernetes resource in parallel. I guess we would need to supply the resourceVersion from the read call before the patch then retry if we get a conflict. 

That being said, perhaps there is an argument for option #2 as in principle each Terraform resource is the manager of what's configured inside it.
