### ISSUE TITLE
Container memory limits are sometimes converted into nonsense values

### ISSUE THREAD

**Issue by marksumm** [hashicorp/terraform-provider-kubernetes#1857]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.6
Kubernetes provider version: 2.12.1
Kubernetes version: 1.23
```

### Affected Resource(s)

kubernetes_deployment_v1

### Steps to Reproduce

Set spec.template.spec.container.resources.limits.memory = "1.1Gi"

### Expected Behavior
spec.template.spec.container.resources.limits.memory should be applied as "1.1Gi"

### Actual Behavior
spec.template.spec.container.resources.limits.memory is applied as "1181116006400m"

### References

Maybe related to this: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/248

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by marksumm** [comment]
If I pretend that millibytes are real, then the value is not nonsense.  The question is why is any unit conversion being performed in the first place?

**Comment by alexsomesan** [comment]
Hi!

This is a conversion done on the Kubernetes API side and it's not deterministic or standardised across various flavours of Kubernetes installations. The provider cannot anticipate if the conversion will be performed and what the end value will be - it's all up to the API server.

You can mitigate this by just taking the value that the API returned and using that in your configuration instead of the one you originally entered.

I know it's not pretty or ideal, but it's not something the provider can influence.

**Comment by marksumm** [comment]
@alexsomesan Fair enough.  Thanks for the explanation!
