### ISSUE TITLE
Perpetual diff on ingress without ingress_class_name

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-kubernetes#1946]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
```

### Affected Resource(s)
- kubernetes_ingress_v1
- kubernetes_ingress

### Steps to Reproduce
1. Have a default ingress class in the cluster
2. Create an ingress resource without `ingress_class_name` defined
3. Apply
4. Apply again, observe a diff

### Expected Behavior
No diff appear

### Actual Behavior
Kubernetes injects ingress class name as default ingress class exists. Terraform attempts to override it

### References
- https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @vladimirtiukhtin,

Thank you for reporting this issue. That happens because `spec.ingress_class_name` is not marked as computed and the provider overwrites it with the default value if it wasn't set. This one should be fixed in the attached PR for the resource `kubernetes_ingress_v1`. `kubernetes_ingress` is a different story.

`kubernetes_ingress_v1` uses `apiVersion: networking.k8s.io/v1` and Kubernetes sets the ingress class name as it is described in the documentation.
`kubernetes_ingress` uses `apiVersion: extensions/v1beta1` and in this case, Kubernetes does not set the ingress class name as it is described in the documentation.

Please let me know if I have missed something related to the resource `kubernetes_ingress`.

Thank you.
