### ISSUE TITLE
Exporting server-side modified annotations results in `Attempt to index null value`

### ISSUE THREAD

**Issue by wombat** [hashicorp/terraform-provider-kubernetes#1951]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.3.5
Kubernetes Provider version: v2.16.1
Kubernetes version: v1.23.12
```
## Terraform configuration
```hcl
resource "kubernetes_namespace" "namespace" {
  metadata {
    name = var.name
  }
}

data "kubernetes_namespace" "namespace" {
  metadata {
    name = kubernetes_namespace.namespace.id
  }
}

output "uid" {
  value = split("/", data.kubernetes_namespace.namespace.metadata[0].annotations["openshift.io/sa.scc.uid-range"])[0]
}

```

## Question
```
Hey folks!
I am building a module that creates a kubernetes namespace on an OpenShift cluster.
After creating the namespace I am trying to export an annotation value, which gets set on the server side by OpenShift, as a Terraform output.
I have tried using the annotations of the namespace resource directly and also via a data resource, but both attempts result in "Error: Attempt to index null value - data.kubernetes_namespace.namespace.metadata[0].annotations is null".

Do you have any hint on what I am doing wrong / how to solve this?

Best
Daniel
```

**Comment by arybolovlev** [comment]
Hi @wombat,

To better understand the problem, can you please share either a piece of the Terraform state file where we can see the mentioned resource and its attributes OR update your output to print out all annotations? For example:

```json
  "resources": [
    {
      "mode": "managed",
      "type": "kubernetes_namespace",
      "name": "namespace",
      "provider": "provider[\"registry.terraform.io/hashicorp/kubernetes\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1951",
            "metadata": [
              {
                "annotations": {
                  "hello": "world"
                },
                "generate_name": "",
                "generation": 0,
```

OR

```hcl
output "namespace" {
  value = kubernetes_namespace.namespace.metadata.0.annotations
}
```

```console
$ terraform apply -auto-approve
...
Outputs:

namespace = tomap({
  "hello" = "world"
})
```
Thanks.

**Comment by wombat** [comment]
@arybolovlev Thanks for your feedback! Unfortunately I can´t apply the mentioned code and therefore don´t have a state file as it is straight failing with:
```
$ terraform apply
╷
│ Error: Attempt to index null value
│
│   on main.tf line 14, in output "uid":
│   14:   value = split("/", data.kubernetes_namespace.namespace.metadata[0].annotations["openshift.io/sa.scc.uid-range"])[0]
│     ├────────────────
│     │ data.kubernetes_namespace.namespace.metadata[0].annotations is null
│
│ This value is null, so it does not have any indices.
```

This is the full terraform code I have currently:
```
resource "kubernetes_namespace" "namespace" {
  metadata {
    name = "wombat-test"
  }
}

data "kubernetes_namespace" "namespace" {
  metadata {
    name = kubernetes_namespace.namespace.id
  }
}

output "uid" {
  value = split("/", data.kubernetes_namespace.namespace.metadata[0].annotations["openshift.io/sa.scc.uid-range"])[0]
}

output "namespace" {
  value = kubernetes_namespace.namespace.metadata.0.annotations
}
```

**Comment by arybolovlev** [comment]
Can you please comment out `output "uid"` and try again? The whole point is to see which annotations you have once created a new namespace.

**Comment by wombat** [comment]
When enabling debug logging I just noticed this message:
```
2023-01-10T16:51:05.625+0100 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value for kubernetes_namespace.namespace, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .metadata[0].annotations: was null, but now cty.MapVal(map[string]cty.Value{"openshift.io/sa.scc.mcs":cty.StringVal("s0:c33,c12"), "openshift.io/sa.scc.supplemental-groups":cty.StringVal("1001080000/10000"), "openshift.io/sa.scc.uid-range":cty.StringVal("1001080000/10000")})
      - .metadata[0].generate_name: was null, but now cty.StringVal("")
```

**Comment by arybolovlev** [comment]
The error you can see here is fine, it is always there. :-)

It looks like the output for the `annotations` is empty, but what about `data_annotations` one? Will that be possible to run this code completely from scratch and share the output?

My assumption of the flow is the following:
1. The provider created a new workspace and the response from Kubernetes returns no annotations;
2. The side controller sets up a set of annotations to the newly created namespace;
3. The provider reads the namespace with annotations;
4. Run the provider again and it will try to remove annotations since they are not managed by Terraform.

I assume that on step (3) it might be something like a raise condition. Basically, if the side controller is fast enough to update the namespace, you should be able to see annotations, if not, you are not going to see them. So here, if you can show the output after the very first run, we will either see or not see annotations.

As of when the provider removes annotations -- it is expected and you might want to use `ignore_annotations` on the provider level. More information is [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#ignore-kubernetes-annotations-and-labels).

**Comment by wombat** [comment]
The terraform code and state file I shared yesterday after you asked me to remove the "output uid" were without any previous state.
From this you can see that the resource itself has `annotations: null` but the annotations are present in the data object - nevertheless the output is empty - I would have expected that at least the output of the data object would be filled and would consider this some kind of race condition.

**Comment by arybolovlev** [comment]
Hi @wombat,

I wanted to give more explanation regarding the observed behavior.

Here is the code I was using to reproduce the issue:

```hcl
resource "kubernetes_namespace" "namespace" {
  metadata {
    name = "1951"
  }
}

data "kubernetes_namespace" "namespace" {
  metadata {
    name = kubernetes_namespace.namespace.id
  }
}

output "data_namespace" {
  value = data.kubernetes_namespace.namespace.metadata.0.annotations
}

output "namespace_annotations" {
  value = kubernetes_namespace.namespace.metadata.0.annotations
}
```

The first apply produces the following output:

```console
$ terraform apply
Terraform will perform the following actions:

  # data.kubernetes_namespace.namespace will be read during apply
  # (config refers to values not yet known)
 <= data "kubernetes_namespace" "namespace" {
      + id   = (known after apply)
      + spec = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = (known after apply)
          + resource_version = (known after apply)
          + uid              = (known after apply)
        }
    }

  # kubernetes_namespace.namespace will be created
  + resource "kubernetes_namespace" "namespace" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "1951"
          + resource_version = (known after apply)
          + uid              = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

kubernetes_namespace.namespace: Creating...
kubernetes_namespace.namespace: Creation complete after 0s [id=1951]
data.kubernetes_namespace.namespace: Reading...
data.kubernetes_namespace.namespace: Read complete after 1s [id=1951]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

As you can see, it does not say anything about 2 outputs that I have in the code and thus they are not available once the code is applied. This is Terraform behavior, not provider and I do not know why it does not produce any outputs. It seems like Terraform doesn't printout `null` outputs, but in this case it would be expected to see at least the one from data source. I think the Terraform folks can better answer this question.

In the Terraform state file we can see that data source has annotations, resource doesn't:

```json
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "kubernetes_namespace",
      "name": "namespace",
      "provider": "provider[\"registry.terraform.io/hashicorp/kubernetes\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1951",
            "metadata": [
              {
                "annotations": {
                  "terraform.io/hello": "world"
                },
...
    {
      "mode": "managed",
      "type": "kubernetes_namespace",
      "name": "namespace",
      "provider": "provider[\"registry.terraform.io/hashicorp/kubernetes\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1951",
            "metadata": [
              {
                "annotations": null,
```

This is something that Terraform does, not the provider. The provider produces consistent results on every run.

Even if Terraform will print out outputs after the first run, it will remove annotations during the following one, as you can see in your outputs. In this case, `ignore_annotations` won't help(I was wrong in my previous comment). With `ignore_annotations` you won't be able to get ignored annotations. I am not sure how OpenShift handles this situation, whether it is going to add annotations again or it does it only once. But in all cases, Terraform will keep deleting them, since they are not managed by Terraform.

This is not something the provider can address, the observed behavior is fully up to Terraform.
