### ISSUE TITLE
disable kubernetes API check during planning phase

### ISSUE THREAD

**Issue by lethargosapatheia** [hashicorp/terraform-provider-kubernetes#1985]
Hello,

I have an issue where I'm provisioning a self-hosted kubernetes cluster through terraform and where I'm adding some custom resources for MetalLB. For this I'm trying to use the terraform kubernetes provider. The reason why I'm doing this and I'm not applying everything in cloudinit (as I do with the other stuff) is that MetalLB starts only after the worker nodes are ready, so if I apply the CRDs through the cloud-init scripts of the controlplane node, it will fail, because the MetalLB controller pod won't be ready.

Therefore I need another "external" solution (i.e. kubernetes provider) to add the CRDs after having provisioned the cluster. Now I've added the kubernetes resources and I've explicitly made them dependent on the other resources, but only later did I realise that the provider is checking if the cluster API is up and running during the planning phase.

It would be great if you offerred the possibilty of optionally disabling this initial check, so that you can use the provider as a complement to the provisioning of the kubernetes cluster.

**Comment by arybolovlev** [comment]
Hi @lethargosapatheia,

If I understand your question correctly, you want to install CRD and deploy related CR in one run. The resource `kubernetes_manifest` is required the CRD to be installed first since it is reading it in order to build schema during the planning phase(more information [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#before-you-use-this-resource)). This cannot be disabled.

Please, use a template while opening an issue.

I will go ahead and close this issue.

Thank you.
