### ISSUE TITLE
kubernetes_node_taint causes kubernetes_labels to crash

### ISSUE THREAD

**Issue by rvdh** [hashicorp/terraform-provider-kubernetes#2023]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v1.3.7
Kubernetes provider version: v2.18.1
Kubernetes version: v1.24
```

### Affected Resource(s)
- kubernetes_node_taint 
- kubernetes_labels 

### Terraform Configuration Files
```hcl
resource "kubernetes_node_taint" "taint_workers_dcc" {
  for_each = toset(local.dcc_workers)

  metadata {
    name = each.key
  }
  taint {
    key    = "zone"
    value  = "onprem-dcc"
    effect = "NoSchedule"
  }
}

resource "kubernetes_labels" "nodes" {
  for_each = local.zone_per_node

  api_version = "v1"
  kind        = "Node"

  metadata {
    name = each.key
  }

  labels = {
    "px/zone"                     = format("onprem-%s", each.value.zone)
    "topology.kubernetes.io/zone" = each.value.zone
  }
}
```

### Debug Output
https://gist.github.com/rvdh/78241f3d16bee881d7bba6b324ef3c00

### Panic Output
https://gist.github.com/rvdh/78241f3d16bee881d7bba6b324ef3c00

### Steps to Reproduce
Use the kubernetes_label resource to add labels to a node. Use the kubernetes_node_taint resource to add a taint to a node.
The first terraform apply, everything works fine. The second terraform apply or plan, terraform crashes because the kubernetes_label resource expect 'metadata' to be present in the managedFields element where 'Terraform' is the manager. But this isn't present so converting it to a map fails.

### Expected Behavior
On the second apply/plan, nothing should have happened (0 changes).

### Actual Behavior
Terraform crashed.

### References
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1921

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
Thanks for opening this issue @rvdh. It looks like this is happening because both of these resources are using service side apply and they are using the same field manager name. I was able to work around this by setting the `field_manager` attribute of the kubernetes_labels, like this: 

```terraform
resource "kubernetes_node_taint" "taint_workers_dcc" {
  metadata {
    name = "minikube"
  }
  taint {
    key    = "zone"
    value  = "onprem-dcc"
    effect = "NoSchedule"
  }
}

resource "kubernetes_labels" "nodes" {
  api_version = "v1"
  kind        = "Node"

  metadata {
    name = "minikube" 
  }

  labels = {
    test = "test"
  }

  field_manager = "Sheneska"
}
```
We need to do two things here: 
- add `field_manager` for kubernetes_node_taint
- fix read function of the kubernetes_labels so that it doesn't panic

**Comment by BBBmau** [comment]
this issue also relates to a bug in kubernetes where by default each list can only have one field manager. I opened an issue for them and they are in the process of getting this fixed.

https://github.com/kubernetes/kubernetes/issues/117142

**Comment by BBBmau** [comment]
I started looking into this more and i noticed another bug that may have occurred in our recent release. In order to get the panic we will now need to do `terraform apply` three times due to `kubernetes_node_taint` needing to be created a second time despite it existing in the tf state file. I'll look more further into this.
