### ISSUE TITLE
`Node_selector_term` and `toleration` instead of `node_selector_terms` and `tolerations`

### ISSUE THREAD

**Issue by bvdboom** [hashicorp/terraform-provider-kubernetes#2066]
I noticed that in the Kubernetes provider and [`kubernetes_pod`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod#node_selector_term) resource, there are at least two attributes that I came across that are singular instead of plural as used in a Kubernetes manifest. 

For example Terraform defines `.spec.affinity.node_affinity.required_during_scheduling_ignored_during_execution.node_selector_term` instead of what you can find in the actual manifest: [`nodeSelectorTerms`](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-with-node-affinity.yaml). The same holds for [`toleration`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod#toleration) (i/o `tolerations`). 

**Question**
Is there any specific reason as to why this is the case? I feel like it's confusing. 

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Kubernetes Provider version: 2.19.0
Kubernetes version: N/A
```
## Terraform configuration
```hcl
0.13+
```

**Comment by alexsomesan** [comment]
Hi! 

You are right, such discrepancies are still present in some resources. They are usually very early resources, implemented a long time ago. Back then, there was a convention throughout Terraform to name list-style attributes as singular because it wasn't possible to populate multiple element values using the square bracket syntax `[A, B, C]`, but rather the attribute singular name would have to be repeated for each element value on the right side of the `=`. 

It would have looked something like this:
```
toleration = {
  effect = ...
  key = ...
  value = ...
}

toleration = {
  effect = ...
  key = ...
  value = ...
}
```

Nowadays this syntax is superfluous as we support the square bracket one properly. Unfortunately, we cannot align the names of these attributes until the next major version bump due to backwards compatibility guarantees.

**Comment by bvdboom** [comment]
Makes sense, thanks @alexsomesan!
