### ISSUE TITLE
Feature Request: GKE Object modification 

### ISSUE THREAD

**Issue by chriswilliams1977** [hashicorp/terraform-provider-kubernetes#221]
Hi Ya,

We have successfully used Terraform to deploy all needed GCP resources, including folders, projects and GKE clusters.

After the cluster provisioning, we would also like to manage the initial setup of some Kubernetes API objects using Terraform. There is a Kubernetes provider for Terraform to do this:

https://www.terraform.io/docs/providers/kubernetes/index.html

Unfortunately this provider has 2 major problems:

1) It does not support all API object kinds that we would like to setup. For example, cluster roles.
2) It can't be used to modify the objects that already exist when the cluster is created. Our case: kube-dns configmap; we need to add stubDomains configuration.

Is this something that is being worked on?

Best
Chris

**Comment by alexsomesan** [comment]
Hi Chris,

Thanks for getting in touch. I think your use case is a very common one. It should definitely be something you can do with this provider.
As you mention, `ClusterRole` resources are not supported yet. This is just because we haven't gotten to it yet. 
If you feel generous, you can try to contribute a PR for it. Otherwise, we'll try to prioritise the work on our side.

As to modifying existing cluster objects, this is technically possible, but you have to be very aware of what this means.
Most importantly, in order to modify such objects, Terraform needs to OWN them. This can be achieved either through Terraform itself creating them (not the case here) or by IMPORTING them into Terraform's state. Once imported into Terraform, no other tools should be touching them. This is a well known requirement for any resources managed by Terraform.

So, assuming your workflow allows for Terraform to own these resources, you first need to import them and then you can mutate them via Terraform.

For details on how the import operation works, see here:
* https://www.terraform.io/docs/import/index.html
* https://www.terraform.io/docs/import/usage.html

**Comment by lesv** [comment]
kNative, if installed using Terraform's Google provider (or some other means), creates a bunch of kubernetes resources that are designed to be modified.  For example the `knative-serving` `config-domain` resource which describes routing.

```
Name:         config-domain
Namespace:    knative-serving
Labels:       serving.knative.dev/release=v0.8.1
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"_example":"################################\n#                              #\n#    EXAMPLE CONFIGURATION     ...

Data
====
_example:
----
example.com: |

example.org: |
  selector:
    app: nonprofit

svc.cluster.local: |
  selector:
    app: secret

Events:  <none>
```
It really doesn't make sense to import from something you've just created.

**Comment by pdecat** [comment]
Somewhat related to #238 (which is about pre-existing namespaces).
Maybe with something like a `kubernetes_config_map_data` resource that would allow to modify the `data` field of a `ConfigMap` that was not created by terraform.
This would probably require the addition of `kubernetes_config_map` datasource for more flexibility.

**Comment by lesv** [comment]
It probably isn't limited to just `config_map`.  I suspect there are other knative things to update, and this will be a general problem in the future.  I like the idea of using data to allow intelligent modification, but I suspect that such resources could get quite complex.

**Comment by tholcman** [comment]
Hi, 
we are in the same situation. We know about import *workaround* but it doesn't work well in fully auto CI/CD environments. We are creating and configuring clusters automatically regularly.

in CI/CD we can use something like 
```
terraform init
terraform state show kubernetes_config_map.kube_dns || terraform import kubernetes_config_map.kube_dns kube-system/kube-dns
...
```
but I have a bad, really bad feeling about it!

Some argument like `allow_overwrite` would be great. It already exists on `aws_route53_record` why shouldn't add it also to `kubernetes_` resources - implementation should be very simple.

**Comment by aareet** [comment]
ClusterRole and Role bindings are now available - if there is no pending ask in the original request, we'll close this issue.
