### ISSUE TITLE
Conditional kubernetes provider resources

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/terraform-provider-kubernetes#2276]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: v1.5.2
Kubernetes Provider version: 2.23.0
Kubernetes version: any
```
## Terraform configuration
```hcl
resource “kubernetes_annotations” “example” {
count = var.create ? 1 : 0
provider = kubernetes.clus1
…
}
```

## Question
```
Using resource like above, If var.create = false, k8s cluster will not be created and kubernetes_manifest resource return
“…dial tcp [::1]:80: connect: connection refused”
so I need to comment out code using terraform kubernetes provider untile cluster is up.

It is possible to define “conditionally” kubernetes provider resource like kubernetes_manifest ?
```

**Comment by alexsomesan** [comment]
@Roxyrob The widely accepted convention for conditionally creating a resource is exactly the pattern that you quoted, namely setting `count = var.create ? 1 : 0`
That being said, the resource `kubernetes_manifest` is somewhat special because it is designed to retrieve the schema of the resource at runtime from the target cluster. Because of this it requires the cluster to already be available at planning time, unlike any other resource in the Kubernetes provider.
Therefore, you have to separate your configuration into two (or more) apply operations, where one creates the cluster and the next one any Kubernetes resources you might need.

Hope that clarifies things a bit. If you need more help, don't hesitate to re-open and ask.

**Comment by Roxyrob** [comment]
Hi @alexsomesan,
i think this is not related to kubernetes_manifest resource only.

I totally separated eks creation from eks configuration but e.g. using module [terraform-aws-modules/terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) I cannot switch eks cluster (create/destroy) with simple "create = false" and count for eks module resource as internally the module code itself uses some terraform kubernetes provider resources (like "kubernetes_config_map_v1_data") and on terraform apply (with "create = false" and so count = 0) returns:

│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connect: connection refused
│
│   with module.eks_clus1[0].kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks_clus1/main.tf line 554, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  554: resource "kubernetes_config_map_v1_data" "aws_auth" {
│

blocking plan and apply.

Flag "create = false" with "count" probably produce kubernetes provider host = unknown on terraform plan ([Conditional kubernetes_manifest resource](https://discuss.hashicorp.com/t/conditional-kubernetes-manifest-resource/57940)) so the error above for any created resources based on kubernetes provider (within terraform state and checked for current/desired state on plan).

Terraform state manipulation (terraform state rm) for these resources before terraform plan/apply or total separation of eks creation code from any other code and use of "terraform destroy", seems the only viable solutions for any code containing Terraform Kubernetes Provider resources. Not an optimal solution but the only one.

I think this is an important limitation for a DRY (resulable on different environments) terraform configuration made flexible by true|false create resources switches.
