### ISSUE TITLE
kubernetes_manifest CRD bootstraping 

### ISSUE THREAD

**Issue by singhbaljit** [hashicorp/terraform-provider-kubernetes#2334]
When creating a CRD with `kubernetes_manifest`, there is an issue with `terraform plan` for the first time if the K8s operator is also applied with the same Terraform.

### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.5.7
Kubernetes provider version: 2.23.0
Kubernetes version: 1.24
```

### Affected Resource(s)
kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "helm_release" "operator" {
  name       = "emqx-operator"
  repository = "https://repos.emqx.io/charts"
  chart      = "emqx-operator"
}

resource "kubernetes_manifest" "broker" {
  depends_on = [helm_release.operator]

  manifest = yamldecode(<<-EOT

apiVersion: apps.emqx.io/v2beta1
kind: EMQX
...
EOT
  )
}

```

### Panic Output
> no matches for kind "EMQX" in group "apps.emqx.io"

### Steps to Reproduce
1. Define the operator and manifest for the CRD within the same Terraform
2. Run `terraform plan`

### Expected Behavior
Plan should not fail as this will work when `terraform apply` is called.

### Actual Behavior
Error is thrown as its not able to recognize the CRD `kind`.

**Comment by BBBmau** [comment]
Hello, thank you for opening this issue @singhbaljit. What you've mentioned is a progressive apply issue where the solution is to do separate terraform applies instead of attempting to do a terraform apply that deals with multiple resources.

In this case you would want to run `terraform apply` for just the `helm_release` and then run a second `terraform apply` for the manifest

I've linked a part of the docs that mentions this [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#before-you-use-this-resource)

**Comment by txtmode** [comment]
> Hello, thank you for opening this issue @singhbaljit. What you've mentioned is a progressive apply issue where the solution is to do separate terraform applies instead of attempting to do a terraform apply that deals with multiple resources.
> 
> In this case you would want to run `terraform apply` for just the `helm_release` and then run a second `terraform apply` for the manifest
> 
> I've linked a part of the docs that mentions this [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#before-you-use-this-resource)

Alternatively use the provider `kubectl` for Kubernetes manifests: https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest
So you can apply in a single terraform apply and you can stop converting Kubernetes yaml resources to hcl
