### ISSUE TITLE
data.kubernetes_nodes should include annotations

### ISSUE THREAD

**Issue by hcsaustrup** [hashicorp/terraform-provider-kubernetes#2336]
### Description

Please consider returning annotations in the `kubernetes_nodes` data source. Currently annotations are returned, but always as an empty object (`{}`).

**Comment by arybolovlev** [comment]
Hi @hcsaustrup,

Thank you for reporting this issue. I was able to reproduce it and isolate a piece of code where it happens.

I am going to bring this up during our triage session so we can evaluate this issue.

Thanks!

**Comment by arybolovlev** [comment]
To add a bit more context here.

- There is a function [flattenMetadata](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/structures.go#L118) that covers multiple use cases when it comes to flattening received metadata.
- This function aims to cover two use cases -- (1) regular Kubernetes object, when we cut out any labels and annotations whose key names end with `kubernetes.io`(more information in out documentation [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod_v1#annotations)), (2) object templates, when we don't cut out any labels and annotations.
- Due to the nature of the `kubernetes_nodes` data source([here](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/data_source_kubernetes_nodes.go#L97-L99) we pass a prefix), it falls under the second scenario, but it covers only object templates and thus fails for the discussed data source.

We need to refactor the `flattenMetadata` function and basically split in into smaller functions to cover different scenarios.

**Comment by arybolovlev** [comment]
@hcsaustrup, in your case, do you expect to see all annotations and labels in this data source or cutting out `kubernetes.io` ones sounds right?

**Comment by hcsaustrup** [comment]
I'm primarily looking for custom annotations and labels we added ourselves - but if it's not a problem, it would be nice to have all of them available, just in case.
