### ISSUE TITLE
Support `PersistentVolumeLastPhaseTransitionTime` feature gate field `lastPhaseTransitionTime` in `PersistentVolumeStatus`

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-kubernetes#2399]
### Description

PersistentVolumeLastPhaseTransitionTime was recently graduated to beta and includes a [new field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#:~:text=lastPhaseTransitionTime%20is%20the%20time%20the%20phase%20transitioned%20from%20one%20to%20another%20and%20automatically%20resets%20to%20current%20time%20everytime%20a%20volume%20phase%20transitions.%20This%20is%20an%20alpha%20field%20and%20requires%20enabling%20PersistentVolumeLastPhaseTransitionTime%20feature.) as part of `PersistentVolumeStatus`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by theloneexplorerquest** [comment]
Hi, I am interested to work on this issue!

**Comment by BBBmau** [comment]
@theloneexplorerquest you're more then welcome to open a PR! We appreciate contributions from the community to improve the provider. We can assist you on PR if needed

**Comment by theloneexplorerquest** [comment]
Hi @BBBmau thanks for message,

From what I understand, for the actual code, I need to have an if-else statement at https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/resource_kubernetes_persistent_volume_v1.go#L243 
eg. `log.Printf("[DEBUG] Persistent volume %s status received: %#v, lastPhaseTransitionTime is %v", out.Name, statusPhase, out.Status.Phase.lastPhaseTransitionTime)`

My question is: do we want to output this attribute in terraform at all? Because I did not see  `PersistentVolumeStatus.message` and `PersistentVolumeStatus.reason` as log. 

I will make the code change and do some test too.

**Comment by BBBmau** [comment]
@theloneexplorerquest it makes sense to include both message and reason as part of the log. You can also add those along with lastPhaseTransitionTime. 

and yes it looks like depending on the phase you'll want the log to output a different message. a failed status would include `message` and `reason`

**Comment by theloneexplorerquest** [comment]
Hi @BBBmau,

I have created the PR, can you take a look?
For such small changes, is acceptance test required?  I wasn't able to get it running with my Kops cluster yet. 😓

**Comment by BBBmau** [comment]
No need for a test since the `stateConf` doesn't have one already made, this is because it's a log output.
