### ISSUE TITLE
In a kubernetes_deployment_v1 with a service account, setting service_account_name = "" or none does not remove the existing service account

### ISSUE THREAD

**Issue by marcosdiez** [hashicorp/terraform-provider-kubernetes#2433]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.5.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/kubernetes v2.26.0
```

### Affected Resource(s)

- kubernetes_deployment_v1

### How to reproduce

1. create or import a `kubernetes_deployment_v1` with a service account (`service_account_name = "something"` )
1. change service_account_name to `""` or `null`
1. `terraform plan`
1. you will see that there are not changes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
By default, every pod has a `default` service account, so even if it is not specified it will use the `default` service account. When the `service_account_name`  is removed from the config or assigned `""` Terraform is not able to differentiate between an empty string or a null value. Additionally, when the changes are re-applied, Terraform reads the Kubernetes resource and see that it still has the `service_account_name` set as `this` . Since the config doesn't set the `service_account_name` because its empty/null, Terraform updates its state file to match the resource's current state which would be `service_account_name = "this"` hence nothing happens.
Being that `service_account_name` is a compute attribute, i.e. if the field is not explicitly set it will take the value from the resource managed by Terraform (which is why it is still assigned to `this` ).
Here is a workaround you can try:
Use a Terraform variable to manage the service account name, with a default value of `default`.
```
resource "kubernetes_deployment_v1" "this" {
  metadata {
    name = "this"
    labels = {
      app = "this"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "this"
      }
    }

    template {
      metadata {
        labels = {
          app = "this"
        }
      }

      spec {
        service_account_name = var.service_account_name
        container {
          image = "nginx"
          name  = "this"
        }
      }
    }
  }
}

variable "service_account_name" {
  description = "Kubernetes Service Account Name"
  type        = string
  default     = "default"
}
```
