### ISSUE TITLE
Deleting Kubernetes provider resources with `terraform apply`

### ISSUE THREAD

**Issue by oponomarov-tu** [hashicorp/terraform-provider-kubernetes#2569]
I'm using [terraform-aws-modules/eks/aws](https://github.com/terraform-aws-modules/terraform-aws-eks) module to provision an EKS cluster. I then use this module's outputs to configure [`kubernetes`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) provider and create a Kubernetes namespace.

I'm attaching the [simplified gist](https://gist.github.com/oponomarov-tu/f6f85516f33b20630a988a9867e39ad1) of what's happening. As you can see from the gist, I'm using a common approach for creating resources conditionally. All works great until I deliberately set `create = false` and attempt to destroy entire stack with `terraform apply`; then all the downstream resources and modules are to be destroyed on a subsequent `terraform apply` -- this causes dependency issue, since the inputs to configure `kubernetes` provider credentials are not available anymore:

    Plan: 0 to add, 0 to change, 140 to destroy.
    
    ╷
    │ Error: Get "http://localhost/api/v1/namespaces/argocd": dial tcp 127.0.0.1:80: connect: connection refused
    │
    │   with module.cell.kubernetes_namespace.argocd[0],
    │   on ../../../../../modules/cell/gitops_bridge.tf line 138, in resource "kubernetes_namespace" "argocd":
    │  138: resource "kubernetes_namespace" "argocd" {

Question: how do I ensure that `kubernetes` provider is still able to connect to the EKS cluster in question and the resources are destroyed in correct order (`kubernetes_namespace` -> `module.eks` -> ...) when using `terraform apply` with `create = false` rather than plain `terraform destroy`? In before you ask why I want this rather than using `terraform destroy` -- we're going to have hundreds of stacks that need be disabled / enabled declaratively.

**Comment by appilon** [comment]
Hello @oponomarov-tu,

It appears you are attempting to perform very dynamic management of interdependent resources across providers. Unfortunately we officially recommend the cluster lifecycle be managed in a separate apply/workspace than the k8s resources themselves. This is a known limitation of TF we continue to try and work on and how providers blocks are configured BEFORE anything is applied (making cross provider single apply configurations very tricky when the output of one is needed to configure the provider block of another). Using a module effectively emulates 2 step apply which is why you are able to build. The gist you provided seems to use locals which might be creating a layer of indirection that is allowing this edgecase to occur?

My only suggestion is within the `depends_on` argument pass it an explicit output of the module and not just reference the module itself (this might be the secret sauce to fix this for you hopefully). I think you can also use a trick referenced [here](https://stackoverflow.com/questions/58275233/terraform-depends-on-with-modules) but this would require you to author the eks module and have a placeholder variable defined in the module to create the dependancy graph link.

```
depends_on = [module.eks.cluster_endpoint]
```

I'm going to close this issue as there is nothing specific about k8s in problem. If you think there is a bug in Core's dependency graph building please follow up and file an issue on [core](https://github.com/hashicorp/terraform/issues/new/choose)
