### ISSUE TITLE
Dynamic probe causes "contains unknown values during apply" error

### ISSUE THREAD

**Issue by bpoland** [hashicorp/terraform-provider-kubernetes#763]
I am trying to make a module that allows configuration of the liveness probe, either`tcp_socket` or `http_get`.  But I can't seem to get it working -- the plan looks alright but when I try to apply I get an error: `configuration for kubernetes_deployment.example still contains unknown values during apply`

### Terraform Version
Terraform v0.12.20
+ provider.kubernetes v1.11.0

### Affected Resource(s)
- kubernetes_deployment

### Terraform Configuration Files
```hcl
variable "namespace" {
  type    = string
}

variable "name" {
  type    = string
}

variable "readiness_probe" {
  default = {
    http_get = {
      path = "/readiness"
      port = "http"
    }
  }
}

resource "kubernetes_deployment" "example" {
  metadata {
    namespace = var.namespace
    name      = var.name
  }

  spec {
    template {
      spec {
        container {
          name  = var.name
          image = "nginx:latest"

          port {
            name           = "http"
            container_port = 8080
          }

          readiness_probe {
            dynamic "tcp_socket" {
              for_each = lookup(var.readiness_probe, "tcp_socket", null)[*]
              content {
                port = tcp_socket.value.port
              }
            }

            dynamic "http_get" {
              for_each = lookup(var.readiness_probe, "http_get", null)[*]
              content {
                path = http_get.value.path
                port = http_get.value.port
              }
            }
          }
        }
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/bpoland/5cd40e200c9e5c96045d4cfbf0445d78

### Panic Output
N/A

### Expected Behavior
Terraform should have applied the configuration, with an http_get liveness probe and no tcp_socket

(also shouldn't have seen all the extra volumes but that is already reported https://github.com/terraform-providers/terraform-provider-kubernetes/issues/685)

### Actual Behavior
`Error: configuration for kubernetes_deployment.example still contains unknown values during apply (this is a bug in Terraform; please report it!)`

### Steps to Reproduce
`terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by dak1n1** [comment]
Thanks for opening this issue, and including the reproducer. It worked to reproduce the issue for me with these versions:

```
Terraform v0.12.28
+ provider.kubernetes v1.11.3
```

What I found in my initial investigation is that the included dynamic blocks will only work if both `tcp_socket` and `http_get` are defined at apply time. However, that produces an invalid Deployment config, since [only one of the options can be specified in a Liveness/Readiness probe](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#probe-v1-core). So it makes sense to try and only pass one of these options into the module, which you're doing.

However, it appears that Terraform core might be failing to do some validation at apply time. It should probably check to see that variables within the `dynamic` block have been defined before attempting to apply them. (It likely already does this, but doesn't look for the specific key defined within the map). We'll need to do some more investigation and possibly look at Terraform core to see where validation can be improved.

**Comment by aareet** [comment]
Searching upstream issues yields quite a few results - https://github.com/hashicorp/terraform/search?q=dynamic+unknown&type=Issues
