### ISSUE TITLE
env vars with secret_key_ref to trigger a container restart if the underlying secret has changed

### ISSUE THREAD

**Issue by rubenstolk** [hashicorp/terraform-provider-kubernetes#866]
Looking at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#secretkeyselector-v1-core, when the underlying secret is managed through terraform and is updated, a restart of the container should be triggered.

- Terraform Version
- Terraform v0.12.x

### Sample HCL
```
resource "kubernetes_secret" "secr" {
  metadata {
    name = "secr"
  }
  data {
    env_var = "hello"
  }
}
resource "kuberenetes_pod" "pod" {
  ...
  spec {
    container {
      env {
        name = "IM_OPTIONAL"
        value_from {
          secret_key_ref {
            name = "secr"
            key = "env_var"
          }
        }
      }
    }
  }
  ...
}
```

Steps to Reproduce
```
$ terraform apply
```

**Comment by dak1n1** [comment]
Since Kubernetes doesn't restart containers when secrets and config maps change, it's not a pattern we're planning to support in the provider. See [issue 737](https://github.com/hashicorp/terraform-provider-kubernetes/issues/737#issuecomment-650810892) for some potential work-arounds and a more thorough explanation.
