### ISSUE TITLE
kubernetes_config_map not marking resource_version argument as "known after apply"

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-kubernetes#871]
FYI opened an SO about this first: https://stackoverflow.com/questions/62155432/terraform-resource-isnt-reading-updated-value-of-another-resource-correctly/62155950?noredirect=1#comment109976201_62155950

When the data in kubernetes_config_map is modified a new resource_version is generated. 

But kubernetes_config_map does not mark resource_version as know after apply as it should. This would be super useful because it makes it easy to trigger a rolling deployment when a config map is changed by merely attaching a label to a kubernetes_deployment with this value

**Comment by pdecat** [comment]
It does not seem currently possible to implement [@apparentlymart's suggestion](https://stackoverflow.com/questions/62155432/terraform-resource-isnt-reading-updated-value-of-another-resource-correctly/62155950?noredirect=1#comment109976201_62155950) with the terraform plugin SDK.

The issue is that `resource_version` is not at the root of the config map resource's schema, it is nested as `metadata.0.resource_version` and `ResourceDiff.SetNewComputed()` only works on non-nested fields: https://github.com/hashicorp/terraform-plugin-sdk/blame/v1.13.1/helper/schema/resource_diff.go#L302 / https://github.com/hashicorp/terraform-plugin-sdk/blame/v2.0.0-rc.1/helper/schema/resource_diff.go#L302

I've experimented a bit and the only way I've identified to have something functional was to duplicate `metadata.0.resource_version` at the root: https://github.com/pdecat/terraform-provider-kubernetes/commit/5ae9199c1f9805b6da7e56bf79d98a77e822016c

Related: https://github.com/hashicorp/terraform-plugin-sdk/issues/459

**Comment by dak1n1** [comment]
Since Kubernetes doesn't restart containers when secrets and config maps change, it's not a pattern we're planning to support in the provider. See [issue 737](https://github.com/hashicorp/terraform-provider-kubernetes/issues/737#issuecomment-650810892) for some potential work-arounds and a more thorough explanation.
